### ISSUE TITLE
[Feature Request] Delete All Cache Entries

### ISSUE THREAD

**Issue by renbaoshuo** [actions/gh-actions-cache#23]
### Describe the feature or problem you’d like to solve

It is good to have an option to delete all cache entries.

### Proposed solution

I think passing `--all` argument is a good solution:

```
gh actions-cache delete --all
```

### Additional context

_None._

**Comment by kotewar** [comment]
Hi @renbaoshuo 👋🏽

Thank you for your wonderful suggestion! :)

Currently we are planning for some enhancements on the current CLI on making it better and I've added your suggestion in list. We will prioritise based on the urgent needs and feedback from other users.

In the meantime, in case you wish to contribute, please feel free to raise a Pull Request for your suggested feature and we will be happy to review the same.

Thanks! :)

**Comment by kotewar** [comment]
We have a similar request #20 opened for the same, hence closing this issue as `duplicate`. We will track the other one for the same. Thanks! :)
