### ISSUE TITLE
It does not work for private repositories

### ISSUE THREAD

**Issue by gugaiz** [actions/gh-actions-cache#26]
### Describe the bug

When running `gh actions-cache list` under the root of a private repo I get:
```
Error: unable to determine current repository, none of the git remotes configured for this repository point to a known GitHub host
```

The origin is set as `git@github.com:<user>/<repo>.git` for fetch and push

**Comment by kotewar** [comment]
Hi @gugaiz, have you logged in into `gh cli` before executing the command?

Please use `gh auth login` to [login to your GitHub](https://cli.github.com/manual/gh_auth_login)  account to be able to access your repo.

**Comment by gugaiz** [comment]
Hi @kotewar, thanks for your answer. I am already logged into `gh`. For example, if I run `gh pr list` on the repo directory, it works

**Comment by kotewar** [comment]
Hi @gugaiz, looks like it is a known thing, please refer [this](https://github.com/cli/cli/issues/2050) and let me know if the problem gets resolved for you.

**Comment by gugaiz** [comment]
@kotewar, not sure if I explain myself right... What I meant was that if I run `gh pr list` I see all the pull requests for my repo, so it means that I am already logged, but if under that same repo I run `gh actions-cache list`, it does not work

**Comment by kotewar** [comment]
What is the output of `git remote -v`?

**Comment by gugaiz** [comment]
```
$ git remote -v
origin	git@github.com:<company>/<repo-name>.git (fetch)
origin	git@github.com:<company>/<repo-name>.git (push)
```

**Comment by kotewar** [comment]
Is your company on GHES (GitHub Enterprise Server) by any chance?

**Comment by gugaiz** [comment]
Not that I am aware of... is there any way to confirm that?

**Comment by kotewar** [comment]
Looking at your origin, it seems you are using the github.com site and not any enterprise instance.

Can you please paste the output of `gh --version`? I am unable to reproduce the issue. Just want to confirm what `gh cli` version you are using.

**Comment by gugaiz** [comment]
```
$ gh --version
gh version 2.14.4 (2022-08-10)
https://github.com/cli/cli/releases/tag/v2.14.4
```
I exported the GH_DEBUG variable but didn't see any output
```
$ export GH_DEBUG=true
$ gh actions-cache list
[actions-cache list] -> [actions-cache list]
Error: unable to determine current repository, none of the git remotes configured for this repository point to a known GitHub host
Usage:
  gh-actions-cache list [flags]

Flags:
  -B, --branch string   Filter by branch
  -h, --help            help for list
      --key string      Filter by key
      --limit int       Number of items to fetch between 1 and 100 (default 30)
      --order string    Order of caches returned (asc/desc)
  -R, --repo string     Select another repository for finding actions cache.
      --sort string     Sort fetched caches (last-used/size/created-at)

**Comment by t-dedah** [comment]
Hi @gugaiz Will it  be possible to explicitly give repo just to confirm where is the problem? Try something like this 

`gh actions-cache -R <org>/<repo-name>`

**Comment by gugaiz** [comment]
Hi @t-dedah I did:
```
$ gh actions-cache list -R <org>/<repo-name>
Error: authentication token not found for host github.com
```
Then I ran:
```
$ gh auth login
? What account do you want to log into? GitHub.com
? You're already logged into github.com. Do you want to re-authenticate? (y/N) y
....
```

Then it worked!, for some reason, that was not very clear, I was already logged but was not working for cache but it did work for another commands.

**Comment by t-dedah** [comment]
Thats awesome @gugaiz

**Comment by gugaiz** [comment]
@t-dedah thanks for all your help!

**Comment by catfishlty** [comment]
@t-dedah 
Hi~
I face the same problem but with `GHES` `3.6.x`. I want to know that how can I solve this problem. Thanks~

```bash
gh actions-cache list -R <[HOST/]owner/repo
Error: authentication token not found for host xxx.xxx.xxx
```

**Comment by VivaLaPanda** [comment]
I am also still seeing this

**Comment by nedtwigg** [comment]
I'm seeing this same error in gh version `2.30.0`, installed the extension just now. The workaround that worked for @gugaiz above did not work for me.

**Comment by zcahana** [comment]
Same here.

```sh
$ gh version
gh version 2.30.0 (2023-05-30)
https://github.com/cli/cli/releases/tag/v2.30.0

$ gh extension list
gh actions-cache  actions/gh-actions-cache  v1.0.3

$ gh actions-cache list --repo redislabsdev/next-gen
Error: authentication token not found for host github.com

$ gh auth login
? What account do you want to log into? GitHub.com
? You're already logged into github.com. Do you want to re-authenticate? Yes
? What is your preferred protocol for Git operations? SSH
? Upload your SSH public key to your GitHub account? Skip
? How would you like to authenticate GitHub CLI? Login with a web browser

! First copy your one-time code: 0E50-42B1
Press Enter to open github.com in your browser...
✓ Authentication complete.
- gh config set -h github.com git_protocol ssh
✓ Configured git protocol
✓ Logged in as zcahana

$ gh actions-cache list --repo redislabsdev/next-gen
Error: authentication token not found for host github.com
```
