### ISSUE TITLE
Error 'The given repo does not exist'

### ISSUE THREAD

**Issue by y4n9squared** [actions/gh-actions-cache#31]
### Describe the bug

Running `gh actions-cache list` yields correct information about cache size but then immediately outputs 'Error: The given repo does not exist'.

```
❯ gh --version
gh version 2.8.0 (2022-04-13)
https://github.com/cli/cli/releases/tag/v2.8.0

❯ gh extensions list
gh actions-cache  actions/gh-actions-cache  v1.0.1
```

### Steps to reproduce the behavior

```
❯ gh actions-cache list                                             
Total caches size 1.69 GB

Error: The given repo does not exist.
```

This is for a private repo running on Github Enterprise Server.

**Comment by bishal-pdMSFT** [comment]
@y4n9squared the extension does not completely support GitHub Enterprise server yet. The plan is to add the support by next ship version i.e. 3.7.

cc @t-dedah @kotewar This should be called out clearly in the README/docs

**Comment by y4n9squared** [comment]
Thanks! Looking forward to the feature.
