### ISSUE TITLE
-L shorthand is not working for list command

### ISSUE THREAD

**Issue by developer-guy** [actions/gh-actions-cache#33]
### Describe the bug

`gh version`: _gh version 2.15.0 (2022-09-06)_
`gh extensions list | grep actions-cache`: _gh actions-cache        actions/gh-actions-cache        v1.0.1_

-L shorthand is not working for the list command

### Steps to reproduce the behavior

1. Execute this command _gh actions-cache list -R developer-guy/buildg -L 100_
2. View the output _Error: unknown shorthand flag: 'L' in -L_
3. Then run _ gh actions-cache list --help_
4. You will notice that the output says you can use the `-L` shorthand for the `--limit` flag.

### Expected vs actual behavior

It should accept the `-L` shorthand for the `--limit` flag.

### Logs

Paste the activity from your command line. Redact if needed.

![Screen Shot 2022-09-16 at 11 34 55 AM](https://user-images.githubusercontent.com/16693043/190595053-c10531a3-4243-418c-82cc-3f72353a56f7.png)
![Screen Shot 2022-09-16 at 11 34 48 AM](https://user-images.githubusercontent.com/16693043/190595062-6f59e17a-2175-43b6-b9f7-9a57acec2ff4.png)

**Comment by kotewar** [comment]
Thanks @developer-guy for bringing this up, it is definitely a bug.
Thanks @devenes from raising a quick PR for the same. Will review it shortly.

**Comment by devenes** [comment]
Thanks @developer-guy for opening this issue and bringing up.
Thanks @kotewar for your quick replies and efforts. 
The pull request (#34) aimed to resolve this bug was successfully merged.

**Comment by developer-guy** [comment]
I'm closing this due to it's fixed by #34
