### ISSUE TITLE
Quickly delete all caches

### ISSUE THREAD

**Issue by electrum** [actions/gh-actions-cache#35]
### Describe the feature or problem you’d like to solve

We had a weird Maven failure in GHA that I suspected was due to a corrupted cache. I wanted to delete all of the caches for Maven. Doing this was more work than expected, since I had to write a shell loop to list the cache keys, parse out the key, then call delete.

### Proposed solution

Adding an option to delete multiple keys would be helpful:

```
gh actions-cache delete --glob 'setup-java-Linux-maven-*'
```

Or even adding a `--all` flag to delete everything.

**Comment by t-dedah** [comment]
Hi @electrum thank you for your wonderful suggestion! :)

Currently, we are planning for some enhancements on the current CLI on making it better and I've added your suggestion in list. We will prioritise based on the urgent needs and feedback from other users.

In the meantime, in case you wish to contribute, please feel free to raise a Pull Request for your suggested feature and we will be happy to review the same.

Thanks! :)

**Comment by w-bonelli** [comment]
for anyone else looking for a [convenient one liner to delete all caches](https://gist.github.com/w-bonelli/f84a18e985eb43175a7c0eecdb442d3f) in the meantime

**Comment by redian** [comment]
In case you want to delete the largest ones first:

```
gh actions-cache list --sort size --order desc | tail -n +5 | cut -f1 | xargs -I@ gh actions-cache delete @ --confirm
```

**Comment by smorimoto** [comment]
This one-liner does it in a simpler way, but also runs it in parallel as many as the number of cores of your machine.


```
gh actions-cache list --limit 100 | awk '{print $1}' | xargs -P $(getconf _NPROCESSORS_ONLN) -I HASH gh actions-cache delete HASH --confirm
```

**Comment by joshmgross** [comment]
👋 This extension is being deprecated in favor of the built-in `gh cache` functionality of the `gh` CLI.

https://github.com/actions/gh-actions-cache/pull/86

This should work in `gh cache` with `gh cache delete --all`.
