### ISSUE TITLE
Clarify how remote is selected

### ISSUE THREAD

**Issue by w-bonelli** [actions/gh-actions-cache#36]
This extension currently uses the `go-gh` module's [`CurrentRepository` function](https://github.com/actions/gh-actions-cache/blob/d3293b69e1c5bc17686d815ab2c64618618c95df/internal/utils.go#L26) to determine the current repo. This function returns the first element of the list returned by the `git.Remotes()` internal function, which [sorts remotes such that `upstream` precedes `github`, which precedes `origin`](https://github.com/cli/go-gh/blob/c2fc965daac88a8a38dd8af02f236095b5dd48f1/internal/git/remote.go#L30). As such, if an `upstream` remote is present, this extension's default behavior is to return its caches, and the user must add `--repo <owner>/<name>` to select their fork's caches.

Maybe it's worthwhile to clarify this in the readme? A user might for instance run `gh repo view` and select their own fork in the interactive prompt, corresponding to remote `origin`, then assume the CLI will propagate that choice down to any extensions.

**Comment by t-dedah** [comment]
Thank you @w-bonelli for the feedback. We will look into this and make the necessary changes.

**Comment by t-dedah** [comment]
PR merged for this one, closing issue
