### ISSUE TITLE
restore-keys: |   npm-feature-${{ hashFiles('package-lock.json') }}   npm-feature-   npm-

### ISSUE THREAD

**Issue by Daphenny** [actions/gh-actions-cache#37]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Actions Cache CLI extension and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by t-dedah** [comment]
Hi @Daphenny can you please add more information about the issue?

**Comment by t-dedah** [comment]
Hi @Daphenny Is this still valid or should we close the issue?
