### ISSUE TITLE
Ability to list cache content

### ISSUE THREAD

**Issue by ssbarnea** [actions/gh-actions-cache#42]
### Describe the feature or problem you’d like to solve

While debugging cache it would be of extremely helpful to know what went into the cache, so we would know if the right files are cached and if the cache size did not grow by caching wrong files.

### Proposed solution

We need a command to list files from the cache and their size.

### Additional context

-

**Comment by t-dedah** [comment]
Hi @ssbarnea you can enable debug mode while caching the files using `actions/cache`, this will list all the files being cached.

**Comment by ssbarnea** [comment]
That is not really a solution for two reasons:
- One would have to rerun a job with debug mode in order to see the files, so no chance of seeing the cache from an existing job
- There is no option to enable debug all the time just for that particular job.
- Most of the time we want to check what is inside a specific cache archive that we think it is too big, that might even be many days or weeks old and we may not be able to clearly determine which job generated it.

That is why I still think that it would be awesome to be able download the archives in order to list their content. Maybe an `inspect` command in the future?

Thanks for the replying!

**Comment by kotewar** [comment]
Hey @ssbarnea, 👋🏽 

You can enable debug logging by following these [steps](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging). This would print all debug logs by default in your workflow runs.
