### ISSUE TITLE
Unable to use branch filter to filter "master" branch caches

### ISSUE THREAD

**Issue by maishiroma** [actions/gh-actions-cache#45]
### Describe the bug

When invoking `gh actions-cache list`, upon specifying `--branch`, the filter only works for specific references. In this case, when specifying `master` for `--branch`, the command returns with: `There are no Actions caches currently present in this repo or for the provided filters`, despite there being caches that have `master` references. However, with any other reference, the command works as expected.

gh cli version
```
gh version 2.20.2 (2022-11-15)
https://github.com/cli/cli/releases/tag/v2.20.2
```

gh extension version
```
gh actions-cache  actions/gh-actions-cache  v1.0.2
```

### Steps to reproduce the behavior

1. Run `gh actions-cache list --branch master` in a repository that contains caches for `master` branch

### Expected vs actual behavior

When running command normally in a repository
```
$ gh actions-cache list --sort last-used --order desc -R  myorg/myrepo
Total caches size 3.36 GB

Showing 5 of 5 cache entries in  myorg/myrepo

Library-XXXX-linuxrunner-unittests-3834242185  665.69 MB  refs/pull/422/merge  17 hours ago
Library-XXXX-linuxrunner-build-3833728933      721.74 MB  master               19 hours ago
Library-XXXX-linuxrunner-build-3833399789      722.02 MB  master               19 hours ago
Library-XXXX-linuxrunner-unittests-3833438332  665.34 MB  refs/pull/393/merge  19 hours ago
Library-XXXX-linuxrunner-unittests-3833399507  665.27 MB  refs/pull/429/merge  20 hours ago
```

What should happen
```
$ gh actions-cache list --branch master
Showing 1 of 1 cache entries in myorg/myrepo

Library-XXXX-linuxrunner-build-3833728933      721.74 MB  master               19 hours ago
Library-XXXX-linuxrunner-build-3833399789      722.02 MB  master               19 hours ago
```

What happens instead
```
$ gh actions-cache list --branch master
There are no Actions caches currently present in this repo or for the provided filters
```

When using a different reference
```
$ gh actions-cache list --branch refs/pull/393/merge
Showing 1 of 1 cache entries in  myorg/myrepo

Library-XXXX-linuxrunner-unittests-3833438332  665.34 MB  refs/pull/393/merge  19 hours ago
```

### Logs

See above output.

**Comment by t-dedah** [comment]
Hi @maishiroma `--branch master` will look for a ref in your repo with name `refs/heads/master`. But the result for `gh actions-cache list --sort last-used --order desc -R  myorg/myrepo` is showing just `master` whereas it should be `refs/heads/master`. 
Can you share a list of all the refs in your repo using this `git show-ref`?

**Comment by maishiroma** [comment]
@t-dedah Thanks for the reply! Of course, this is what I get after running `git show-ref` (truncated output since there's a lot of branches in the repository I'm working in)

```
$ git show-ref

4370801df649feb67cfa3997edef107e49b220be refs/heads/master
250f3e68b1edc3dbbd8a2f99e751d0d4f72e02c3 refs/heads/ms/cache_update_5
4370801df649feb67cfa3997edef107e49b220be refs/remotes/origin/HEAD
153d5c0b400ce631e244a8ac32cb3319430d395e refs/stash
3316f360d159733afb09893b27c3d0ea47296fea refs/tags/3.2.4
ed27ffa15654d4e004f2e2aad1344009e818b709 refs/tags/3.0.22
...
```

One more thing that I wanted to point out is that when you suggested
> --branch master will look for a ref in your repo with name refs/heads/master

I went ahead and tried to use `--branch refs/heads/master` in the `gh actions-cache list` command, and it unfortunatly did not yield any new outputs.

```
$ gh actions-cache list --branch refs/heads/master
There are no Actions caches currently present in this repo or for the provided filters
```

**Comment by t-dedah** [comment]
@maishiroma So you have `refs/heads/master` which is good but not getting any data for `--branch refs/heads/master` still doesnt get us close to the issue. This just means we have no caches for `refs/heads/master` which is expected as shown in the result of `gh actions-cache list --sort last-used --order desc -R  myorg/myrepo`.

Can you please scroll through the list of `git show-ref` and confirm if you have any ref with just `master`.

**Comment by maishiroma** [comment]
@t-dedah Ah my apologies, I should have clarified in my earlier comment when I ran `git show-ref` in my repository.

When running that command, I did **not** see any references named `master`. The closest one were `refs/heads/master` and `refs/remotes/origin/master`.

**Comment by t-dedah** [comment]
Thank you @maishiroma for the clarification. We are investigating this issue atm.

**Comment by t-dedah** [comment]
Hi @maishiroma In order to dig further, will it be possible for you to share workflow run logs which leads to creation of the said cache?

**Comment by t-dedah** [comment]
Hi @maishiroma closing issue for now, feel free to reopen if you are still facing this issue.
