### ISSUE TITLE
This is a great tool, but I'd also like to see a way to do the same with repo artifacts

### ISSUE THREAD

**Issue by StephenHodgson** [actions/gh-actions-cache#48]
### Describe the feature or problem you’d like to solve

The same kind of tool but for artifacts instead of cache

### Proposed solution

How will it benefit Actions Cache CLI extension and its users?
Probably will be a new repo, but could be here too I guess.

**Comment by t-dedah** [comment]
Hi @StephenHodgson thank you for the feedback. This repo is specifically for actions cache but you can still raise an issue with customer-feedback team in this [repo](https://github.com/github/customer-feedback). This should allow others to lend support for the above functionality.

**Comment by StephenHodgson** [comment]
The link you provided is 404

**Comment by t-dedah** [comment]
@StephenHodgson Sorry for the broken link, please use this community discussion & product feedback page to raise your request.
https://github.com/orgs/community/discussions

**Comment by StephenHodgson** [comment]
https://github.com/orgs/community/discussions/45249
