### ISSUE TITLE
Add date filter

### ISSUE THREAD

**Issue by tpak** [actions/gh-actions-cache#51]
### Describe the feature or problem you’d like to solve

I would like to see all cache's created before or after a certain date. 

### Proposed solution

add a flag such as:

--age \<string\>         Return caches older than age (1m/2m/1d/2d/xd/1h/6h/xh)

Where the number of months/days/hours is variable and there are options for month/day/hours of age (perhaps minutes)

### Additional context

It would benefit users so that we can list old caches and then delete them in a script or understand which branch or branches are aging. This could be combined with a bulk delete operation, as discussed in #20 but would also be useful on the list and delete command.

As I have been configuring cache cleanup jobs, I would like to clean up only caches older than a certain number of days/hours so that branches with high current activity levels do not have their caches deleted unnecessarily. This requires unnecessarily complex pipes to external utilities such as awk/grep etc. 

We currently get this type of answer back and need to parse that and cut it down - sometimes it says minutes, hours, or days making it awkward to write a simple script. 

```

gh actions-cache list --order asc --sort last-used -R https://github.com/organization1234/repo8765

Linux-build-cache-node-modules-d627a4016d488c214...  149.00 MB  refs/heads/development  21 hours ago
Linux-build-cache-node-modules-d627a4016d488c214...  149.16 MB  refs/heads/staging      21 hours ago
```

**Comment by joshmgross** [comment]
👋 This extension is being deprecated in favor of the built-in `gh cache` functionality of the `gh` CLI.

https://github.com/actions/gh-actions-cache/pull/86

If this is something you'd like `gh cache` to support, please file an issue in https://github.com/cli/cli.
