### ISSUE TITLE
Tests don't pass when executed from tarball

### ISSUE THREAD

**Issue by twz123** [actions/gh-actions-cache#53]
### Describe the bug

Tests don't pass when executed from tarball.

### Steps to reproduce the behavior

`docker run --rm -it golang:1.20.0-alpine3.17 sh -c 'wget -O- https://github.com/actions/gh-actions-cache/archive/refs/tags/v1.0.3.tar.gz | tar xzvC /tmp && cd /tmp/gh-actions* && go test -v ./...' 2>&1 > result.txt`

There are quite some test failures.

### Expected vs actual behavior

The tests pass. This is typically the way that package maintainers build/test binaries, so it would be beneficial if tests would pass.

### Logs

[result.txt](https://github.com/actions/gh-actions-cache/files/10684898/result.txt)

**Comment by t-dedah** [comment]
Hi @twz123 the rest client in the extension needs GH_TOKEN to run properly. So adding this in the command will fix all the issues.

Try this :-

`docker run --env GH_TOKEN=dummy-token-to-facilitate-rest-client --rm -it golang:1.20.0-alpine3.17 sh -c 'wget -O- https://github.com/actions/gh-actions-cache/archive/refs/tags/v1.0.3.tar.gz | tar xzvC /tmp && cd /tmp/gh-actions* && go test -v ./...' 2>&1 > result.txt`
