### ISSUE TITLE
Support for GitHub Enterprise Server

### ISSUE THREAD

**Issue by iptizer** [actions/gh-actions-cache#55]
# gh-actions-cache Feedback

The support for "GitHub Enterprise Server" is a bit unclear. On the one side the README of this repository states:

```
Note: This extension currently supports github.com only, GitHub Enterprise Server is not supported currently.
```

On the other hand, the [release notes of "GitHub Enterprise Server 3.7"](https://docs.github.com/enterprise-server@3.7/admin/release-notes#github-actions) states as follows:

```
GitHub Actions users who use dependency caching to speed up workflows can now use the GitHub CLI to manage the GitHub Actions cache for a repository. To manage caches using the GitHub CLI, install the gh-actions-cache extension. For more information, see the [gh-actions-cache documentation](https://github.com/actions/gh-actions-cache#readme).
```

Is there maybe an update of the README missing, or is there a missunderstanding on my side in regards to the documentation?

Thanks in advance for your answer!

**Comment by t-dedah** [comment]
Hi @iptizer thank you for filing this issue, yes the extension will work with the latest GHES release. Ill update the readme to reflect that.
