### ISSUE TITLE
version `GLIBC_2.32' not found on Debian bullseye

### ISSUE THREAD

**Issue by jooola** [actions/gh-actions-cache#56]
### Describe the bug

I am unsure if this tool can be used on desktops, but I tried to install the extension on Debian bullseye, and when running an actions cache command, the command fails with the following logs:

```sh
$ gh actions-cache list                             
/home/jo/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/jo/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache)
/home/jo/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/jo/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache)
```

And it seems Debian bullseye have a previous version of glibc:
```sh
$ sudo apt-cache policy libc6 libc-bin
libc6:
  Installed: 2.31-13+deb11u5
  Candidate: 2.31-13+deb11u5
  Version table:
 *** 2.31-13+deb11u5 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        500 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
        100 /var/lib/dpkg/status
libc-bin:
  Installed: 2.31-13+deb11u5
  Candidate: 2.31-13+deb11u5
  Version table:
 *** 2.31-13+deb11u5 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        500 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

### Steps to reproduce the behavior

1. Install the extension on Debian bullseye
2. Run `gh actions-cache list `
3. See error

### Expected vs actual behavior

I would expect the extension to work on Debian bullseye.

**Comment by t-dedah** [comment]
Thank you @jooola for bringing this up. As per our preliminary investigation, we suspect the issue is happening as the package was compiled using ubuntu-22 which uses GLIBC_2.32 whereas Debian is still on GLIBC_2.31. 

Will you be able to confirm if [1.0.2](https://github.com/actions/gh-actions-cache/releases/tag/v1.0.2) for the extension is working fine on Debian bullseye?

**Comment by jooola** [comment]
After uninstalling and pinning the version to 1.0.1, the extension is indeed working.

**Comment by t-dedah** [comment]
Thanks for the confirmation @jooola we will need some more time to finalize changes.

**Comment by myitcv** [comment]
The problem here appears to be that the `linux/amd64` version is built with `CGO_ENABLED=1`, whereas for `linux/arm64` (at least) it is not.

```
$ cd $(mktemp -d)
$ curl -sLO https://github.com/actions/gh-actions-cache/releases/download/v1.0.3/linux-arm64
$ curl -sLO https://github.com/actions/gh-actions-cache/releases/download/v1.0.3/linux-amd64
$ go version -m ./linux-amd64 | grep CGO_ENABLED
        build   CGO_ENABLED=1
$ go version -m ./linux-arm64 | grep CGO_ENABLED
        build   CGO_ENABLED=0
```

Is there a reason the `linux/amd64` version is not built with `CGO_ENABLED=0`?

**Comment by proppy** [comment]
Something similar also seems to be happening un ubuntu20.04 when using larger dedicated runners:
```
Current runner version: '2.303.0'
Runner name: 'ubuntu-[2](https://github.com/google/xls/actions/runs/4634539949/jobs/8200889388#step:1:2)0.04-64core_1eb[3](https://github.com/google/xls/actions/runs/4634539949/jobs/8200889388#step:1:3)2a3c1924'
Runner group name: 'large-runner'
Machine name: 'runner'
```
See the error message below:
```
/home/runner/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache)
/home/runner/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/runner/.local/share/gh/extensions/gh-actions-cache/gh-actions-cache)
```

**Comment by wjdix** [comment]
Given that a fix for this has been committed into main, is there an update to be shared on when the next version, including the fix, might be released?
