### ISSUE TITLE
Feature request: Pagination support

### ISSUE THREAD

**Issue by erezrokah** [actions/gh-actions-cache#75]
### Describe the feature or problem you’d like to solve

Thank you for this great extension to the GitHub CLI. Currently the list command is limited to 100 caches (30 by default), which can easily be reached on monorepo PRs (for example a PR that updates dependencies in multiple monorepo components).

### Proposed solution

Have the list command paginate over the results, the code is already there 😄 
https://github.com/actions/gh-actions-cache/blob/281c73efa0e8fd2c4c779960a06d50109ef309f4/service/actions_cache.go#L72

### Additional context

As a workaround I could use `gh api` directly

**Comment by joshmgross** [comment]
👋 This extension is being deprecated in favor of the built-in `gh cache` functionality of the `gh` CLI.

https://github.com/actions/gh-actions-cache/pull/86

If this is something you'd like `gh cache` to support, please file an issue in https://github.com/cli/cli.
