### ISSUE TITLE
Error: authentication token not found for host github.com

### ISSUE THREAD

**Issue by hakonhagland** [actions/gh-actions-cache#77]
I just installed `gh` on Ubuntu 22.04:
```
$ gh --version
gh version 2.32.1 (2023-07-24)
https://github.com/cli/cli/releases/tag/v2.32.1
```
I ran the `auth login` command:
```
$ gh auth login
? What account do you want to log into? GitHub.com
? What is your preferred protocol for Git operations? SSH
? Upload your SSH public key to your GitHub account? /home/hakon/.ssh/id_rsa.pub
? Title for your SSH key: GitHub CLI
? How would you like to authenticate GitHub CLI? Login with a web browser
[...]
Opening in existing browser session.
✓ Authentication complete.
- gh config set -h github.com git_protocol ssh
✓ Configured git protocol
✓ SSH key already existed on your GitHub account: /home/hakon/.ssh/id_rsa.pub
✓ Logged in as hakonhagland
```
I did some short tests, like setting the default repository for my current directory `gh repo set-default` and verified that I could run `gh pr status` for example. 

Then I installed `actions-cache`:
```
$ gh extension install actions/gh-actions-cache
✓ Installed extension actions/gh-actions-cache

$ gh extension list
gh actions-cache  actions/gh-actions-cache  v1.0.3
```

If I now run `actions-cache list` I get an error:

```
$ gh actions-cache list
Error: authentication token not found for host github.com
```

**Comment by paulschreiber** [comment]
I am having the same problem on macOS 13.5 with gh 2.32.1 and actions/gh-actions-cache 1.0.3.

**Comment by Abirdcfly** [comment]
same here:
gh version 2.32.1 (2023-07-24)
macOS 13.5.1 (22G90)
actions/gh-actions-cache  v1.0.3

**Comment by Abirdcfly** [comment]
```
# gh auth token 
gho_xxxxx
 
# export GITHUB_TOKEN=gho_xxxx
```

gh-actions-cache works fine after setting token as an environment variable...

**Comment by adam-grant-hendry** [comment]
> Appears the action does not account for users that auth login with the browser rather than a token.

Actually I take that back...neither way of using `gh auth login` affects this...Seems you must use @Abirdcfly 's method...

**Comment by spenserblack** [comment]
Last release was in January. Since the latest release, [`go-gh` was upgraded](https://github.com/actions/gh-actions-cache/commit/d88f49218fd18a37f6f63ee4f8716764316a7f7d). IIRC because `gh` updated its auth token storage to a more secure method, all extensions that need tokens need to upgrade `go-gh` (https://github.com/actions/gh-actions-cache/issues/59). In other words, I think creating a new release with the updated dependency would fix this issue.

**Comment by joshmgross** [comment]
👋 This extension is being deprecated in favor of the built-in `gh cache` functionality of the `gh` CLI.

https://github.com/actions/gh-actions-cache/pull/86

If you're experiencing this issue with `gh cache`, please file an issue in https://github.com/cli/cli.
