### ISSUE TITLE
Document that `actions: read/write` permissions are required to use gh-actions-cache in gh actions CI

### ISSUE THREAD

**Issue by corneliusroemer** [actions/gh-actions-cache#85]
I tried to use gh-actions-cache in a Github action.

It failed with:

```
Error: Resource not accessible by integration.
```

It's not immediately clear which permission I needed to give to the action so it works.

After consulting the docs at https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-actions I figured out, I needed to give:

```yaml
permissions:
  actions: write
```

but this wasn't documented anywhere explicitly.

Would be great to add this to the README.

**Comment by joshmgross** [comment]
👋 This extension is being deprecated in favor of the built-in `gh cache` functionality of the `gh` CLI.

https://github.com/actions/gh-actions-cache/pull/86

If you're experiencing this issue with `gh cache`, please file an issue in https://github.com/cli/cli.
